// Copyright 2023 KrainNeun (@KrainNeun)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/* 分割キーボード */
#define MASTER_LEFT
#define SOFT_SERIAL_PIN D2
#define LAYER_STATE_8BIT
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

# define TAPPING_TERM 200
# define TAPPING_TOGGLE 2

/* ポインティングデバイス */
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define PMW33XX_CS_PIN           B6
#define PMW33XX_CPI 1600
// Left Side
#define POINTING_DEVICE_ROTATION_180
// Right Side
// #define POINTING_DEVICE_ROTATION_270
#define POINTING_DEVICE_INVERT_X
// SCLK B1
// MOSI B2
// MISO B3
#define ROTATIONAL_TRANSFORM_ANGLE 30

/* RGB */
#define WS2812_DI_PIN D3
#ifdef RGB_MATRIX_ENABLE
#   define RGB_MATRIX_LED_COUNT 38
#   define RGB_MATRIX_SPLIT { 19, 19 }
#   define SPLIT_TRANSPORT_MIRROR
#   define RGB_MATRIX_MAXIMUM_BRIGHTNESS 128
#   define RGB_DISABLE_WHEN_USB_SUSPENDED
#   define RGB_MATRIX_KEYPRESSES
#   define RGB_MATRIX_DEFAULT_VAL 128
#   define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#   define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_GRADIENT_UP_DOWN
#   define RGB_MATRIX_DEFAULT_SPD 64

#   undef ENABLE_RGB_MATRIX_BREATHING
#   undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#   undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#   undef ENABLE_RGB_MATRIX_BAND_SAT
#   undef ENABLE_RGB_MATRIX_BAND_VAL
#   undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#   undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#   undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#   undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#   undef ENABLE_RGB_MATRIX_CYCLE_ALL
#   undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#   undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#   undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#   undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#   undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#   undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#   undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#   undef ENABLE_RGB_MATRIX_DUAL_BEACON
#   undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#   undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#   undef ENABLE_RGB_MATRIX_RAINDROPS
#   undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#   undef ENABLE_RGB_MATRIX_HUE_BREATHING
#   undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#   undef ENABLE_RGB_MATRIX_HUE_WAVE
#   undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#   undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#   undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#   undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#   undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#   undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#   undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#   undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#   undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#   undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#   undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#   undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#   undef ENABLE_RGB_MATRIX_SPLASH
#   undef ENABLE_RGB_MATRIX_MULTISPLASH
#   undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#   undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif