# 分割キーボード
SPLIT_KEYBOARD = yes
EXTRAKEY_ENABLE = yes

# ポインティングデバイス
MOUSEKEY_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = adns5050

# RGB
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no

# ビルドオプションを設定する
LTO_ENABLE = yes
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no